//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC_OgrenciKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OGRID { get; set; }
        public string OGRAD { get; set; }
        public string OGRSOYAD { get; set; }
        public string OGRMAIL { get; set; }
        public string OGRFOTOGRAF { get; set; }
        public string OGRADRES { get; set; }
    }
}
